### ISSUE TITLE
[bug] You cannot use AsyncToSync in the same thread as an async event loop

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-notifications#81]
This is appearing in a VM running openwisp-notifications dev branch.

```
raised unexpected: RuntimeError('You cannot use AsyncToSync in the same thread as an async event loop - just await the async function directly.')
Traceback (most recent call last):
  File "/opt/openwisp2/env/lib/python3.8/site-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/openwisp2/env/lib/python3.8/site-packages/celery/app/trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/openwisp2/env/lib/python3.8/site-packages/openwisp_notifications/tasks.py", line 27, in delete_obsolete_notifications
    Notification.objects.filter(where).delete()
  File "/opt/openwisp2/env/lib/python3.8/site-packages/django/db/models/query.py", line 722, in delete
    deleted, _rows_count = collector.delete()
  File "/opt/openwisp2/env/lib/python3.8/site-packages/django/db/models/deletion.py", line 337, in delete
    signals.post_delete.send(
  File "/opt/openwisp2/env/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 173, in send
    return [
  File "/opt/openwisp2/env/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 174, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/opt/openwisp2/env/lib/python3.8/site-packages/openwisp_notifications/handlers.py", line 172, in clear_notification_cache
    ws_handlers.notification_update_handler(
  File "/opt/openwisp2/env/lib/python3.8/site-packages/openwisp_notifications/websockets/handlers.py", line 13, in notification_update_handler
    async_to_sync(channel_layer.group_send)(
  File "/opt/openwisp2/env/lib/python3.8/site-packages/asgiref/sync.py", line 76, in __call__
    raise RuntimeError(
RuntimeError: You cannot use AsyncToSync in the same thread as an async event loop - just await the async function directly.
```

**Comment by nemesisdesign** [comment]
This was a bug in ansible-openwisp2, fixed by https://github.com/openwisp/ansible-openwisp2/pull/254.
